# -*- coding: utf-8 -*-
"""Задание 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cjgSX5Nh8asx-sg0iLP-fd7FdVKGhb7H

Фарков Дмитрий Викторович КИ-19-20Б
"""

print("Hello world")